services:
  - type: web
    name: pcm-buddy
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn pcm_buddy.wsgi"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key-here
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com